### ISSUE TITLE
Dynamic script variables

### ISSUE THREAD

**Issue by tweekmonster** [mhinz/vim-lookup#1]
Different ways script variables can be defined:

```vim
let s:variable_name = 0
let s:{variable}_name = 0
let s:['variable_name'] = 0
```

They can be defined in any scope within the script.

They can also be defined like this:

```vim
exe[cute] 'let s:variable_name = 0'
```

but it shouldn't matter if the search is for `\<let s:\>`

**Comment by tweekmonster** [comment]
My suggestion for partial matches is to split the variable name into alphanumeric chunks:

```
variable_name_123 -> ['variable', 'name', '123']
```

They could be matched using some sort of fuzzy search.

**Comment by mhinz** [comment]
;>

**Comment by tweekmonster** [comment]
![emot-argh](https://cloud.githubusercontent.com/assets/111942/22214261/0e20a822-e165-11e6-9ca1-b5316bb984d2.gif)

**Comment by mhinz** [comment]
😘
