### ISSUE TITLE
will vim-lookup support no-autoload func?

### ISSUE THREAD

**Issue by L-stt** [mhinz/vim-lookup#6]
I hope vim-lookup support func name like `Testfunc()`, just use `:verbose function Testfunc` to get where the function is definitioned.

**Comment by mhinz** [comment]
Should be doable. I look into it later today.

Thanks for bringing this up!

**Comment by mhinz** [comment]
Please update the plugin and see if it works as expected.

**Comment by L-stt** [comment]
nice, it works well for me.
